import React from 'react';

const EthicalWarning: React.FC = () => {
  return (
    <div className="bg-amber-50 border-l-4 border-amber-500 p-4 my-4 rounded-r shadow-sm">
      <div className="flex">
        <div className="flex-shrink-0">
          <svg className="h-5 w-5 text-amber-400" viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
          </svg>
        </div>
        <div className="ml-3">
          <h3 className="text-sm leading-5 font-medium text-amber-800">
            AI Clinical Insight Disclaimer
          </h3>
          <div className="mt-2 text-sm leading-5 text-amber-700">
            <p>
              This content was generated by Artificial Intelligence (Gemini). It is intended for documentation assistance only and <strong>must not</strong> be used as a substitute for professional medical diagnosis or advice. A qualified healthcare provider must review all outputs.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EthicalWarning;